
drop table if exists PROJECTS;
drop table if exists PARTNERS;
drop table if exists STUDENTS;
/* ------------------------------------- PROJECT DATABASE TABLE -------------------------------------- */
CREATE TABLE IF NOT EXISTS PROJECTS (
	ID INTEGER PRIMARY KEY,
	TITLE VARCHAR(64) DEFAULT '' NOT NULL,
    PARTNER VARCHAR(64) DEFAULT '' NOT NULL,
    LOCATION VARCHAR(80) DEFAULT '' NOT NULL,
    FIELD VARCHAR(64) DEFAULT '' NOT NULL,
    DESCRIPTION VARCHAR(300) DEFAULT '' NOT NULL,
	STUDENT_NUM INTEGER DEFAULT '0' NOT NULL,
    APP_NUMBER INTEGER DEFAULT '0' NOT NULL,
    PARTNER_ID INTEGER DEFAULT '0' NOT NULL
    );
/* ------------------------------------- PARTNER DATABASE TABLE -------------------------------------- */
CREATE TABLE IF NOT EXISTS PARTNERS (
	ID INTEGER PRIMARY KEY,
	COMPANY VARCHAR(64) DEFAULT '' NOT NULL,
	LOCATION VARCHAR(80)
    );
/* ------------------------------------- STUDENT DATABASE TABLE -------------------------------------- */
CREATE TABLE IF NOT EXISTS STUDENTS (
	ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(64) DEFAULT '' NOT NULL,
    LAST_NAME VARCHAR(64) DEFAULT '' NOT NULL,

    PROJECT_A INTEGER DEFAULT '0',
    TITLE_A VARCHAR(300) DEFAULT '' NOT NULL,
    PARTNER_A VARCHAR(300) DEFAULT '' NOT NULL,
    JUST_TEXT_A VARCHAR(300) DEFAULT '' NOT NULL,

    PROJECT_B INTEGER DEFAULT '0',
    TITLE_B VARCHAR(300) DEFAULT '' NOT NULL,
    PARTNER_B VARCHAR(300) DEFAULT '' NOT NULL,
    JUST_TEXT_B VARCHAR(300) DEFAULT '' NOT NULL,

    PROJECT_C INTEGER DEFAULT '0',
    TITLE_C VARCHAR(300) DEFAULT '' NOT NULL,
    PARTNER_C VARCHAR(300) DEFAULT '' NOT NULL,
    JUST_TEXT_C VARCHAR(300) DEFAULT '' NOT NULL
    );
